linter:
  rules:
    - annotate_overrides
    - hash_and_equals
    - prefer_is_not_empty
    - prefer_is_empty
    - prefer_single_quotes
    - prefer_spread_collections
    - prefer_typing_uninitialized_variables
    - prefer_void_to_null
    - prefer_is_not_operator
    - prefer_iterable_whereType
    - camel_case_extensions
    - cancel_subscriptions
    - camel_case_types
    - avoid_empty_else
    - avoid_returning_null_for_void
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - exhaustive_cases
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_getters_setters
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_statements
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_this
    - unrelated_type_equality_checks
    - use_full_hex_values_for_flutter_colors
    - use_is_even_rather_than_modulo
    - use_late_for_private_fields_and_variables
    - use_raw_strings
    - use_rethrow_when_possible
    - valid_regexps
    - void_checks
analyzer:
  errors:
    camel_case_types: error
    missing_required_param: error
    missing_return: warning
    todo: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"